import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
  icons: {
    icon: "../images/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen font-sans">
      {/* Sidebar */}

      <Sidebar />
      <div className="overflow-y-auto w-full">{children}</div>
    </div>
  );
}
