import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "@fontsource-variable/space-grotesk";
import Sidebar from "./components/Sidebar";

import { Toaster } from "@/components/ui/sonner";
// import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
  icons: {
    icon: "../images/logo.svg", // or .png or any image
  },
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen font-sans">
      {/* Sidebar */}

      <Sidebar />
      <div className="overflow-y-auto w-full">{children}</div>

      {/* <ToastContainer position="top-right" autoClose={3000} /> */}
    </div>
  );
}
